const KEY='kerolosDietPwa.v1';
const todayKey=()=>new Date().toISOString().slice(0,10);
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const defaultTasks=[
 {id:crypto.randomUUID(),time:'10:00',title:'كونترلوك',details:'قبل الفطار بساعة',type:'med'},
 {id:crypto.randomUUID(),time:'10:30',title:'٢ كوب مياه',details:'قبل الفطار',type:'water'},
 {id:crypto.randomUUID(),time:'11:00',title:'الفطار',details:'رغيف بلدي + اختيار واحد: ٤ معالق فول بدون زيت / ٢ طعمية فرن / نصف بطاطسية مسلوقة + خيار وخس مفتوح',type:'meal'},
 {id:crypto.randomUUID(),time:'13:00',title:'اسناك',details:'ثمرة فاكهة أو اسناك واحد من الصور أو كوب عصير بدون سكر',type:'snack'},
 {id:crypto.randomUUID(),time:'15:00',title:'سيبروفار',details:'بعد الأكل - راجع الطبيب لو التوقيت يحتاج تعديل',type:'med'},
 {id:crypto.randomUUID(),time:'15:10',title:'فلاجيل',details:'بعد سيبروفار بـ 10 دقائق',type:'med'},
 {id:crypto.randomUUID(),time:'18:30',title:'٢ كوب مياه',details:'قبل العشاء',type:'water'},
 {id:crypto.randomUUID(),time:'19:00',title:'الغداء/العشاء',details:'رغيف أو ٧ معالق رز/مكرونة + اختيار واحد: مشروم / بطاطس / بتنجان / فاصوليا / ٤ معالق ملوخية / سمكة مشوية + نصف رغيف',type:'meal'},
 {id:crypto.randomUUID(),time:'21:00',title:'سيبروفار',details:'جرعة مسائية - راجع الطبيب لأن 12 ساعة بدقة قد تحتاج ترتيب مختلف',type:'med'},
 {id:crypto.randomUUID(),time:'21:10',title:'فلاجيل',details:'بعد سيبروفار بـ 10 دقائق',type:'med'},
 {id:crypto.randomUUID(),time:'22:00',title:'مشي سريع',details:'٤٠ دقيقة',type:'walk'},
 {id:crypto.randomUUID(),time:'23:00',title:'ممنوع الأكل',details:'مياه فقط عند الحاجة',type:'stop'}
];
const defaultState={activeProgramId:'p1',settings:{sound:true,vibrate:true},programs:[{id:'p1',name:'P1',start:'2026-06-26',end:'2026-07-05',instructions:'شرب ٣ لتر يوميًا = ١٢ كوب ماء، منهم ٢ كوب قبل كل وجبة. الأكل في أواني صغيرة. عند الجوع مسموح سلطة خضراء. ممنوع المسبك. ممنوع الأكل بعد الساعة 11. المشي خطوة سريعة 40 دقيقة يوميًا. الميزان فقط في الموعد المحدد قبل الفطار وبعد دخول الحمام.',tasks:defaultTasks}],done:{},water:{},weights:[],snacks:[]};
let state=load();let editingId=null;let timers=[];let deferredPrompt=null;
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function activeProgram(){return state.programs.find(p=>p.id===state.activeProgramId)||state.programs[0];}
function showToast(msg){$('#toast').textContent=msg;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2600)}
function icon(type){return {med:'💊',water:'💧',meal:'🍽️',snack:'🍎',walk:'🚶',stop:'⛔'}[type]||'⏰'}
function render(){const p=activeProgram();$('#activeProgramTitle').textContent=p.name;$('#programDates').textContent=`من ${p.start||'—'} إلى ${p.end||'—'}`;renderTimeline();renderWater();renderPrograms();renderSnacks();renderWeights();scheduleTodayAlarms();}
function renderTimeline(){const p=activeProgram();const done=state.done[todayKey()]||{};$('#timeline').innerHTML=p.tasks.sort((a,b)=>a.time.localeCompare(b.time)).map(t=>`<div class="task ${done[t.id]?'done':''}"><button class="check" data-done="${t.id}">${done[t.id]?'✓':''}</button><div><div class="task-title">${icon(t.type)} ${t.title}</div><div class="task-details">${t.details||''}</div></div><div class="time">${to12(t.time)}</div></div>`).join('');$$('[data-done]').forEach(b=>b.onclick=()=>{state.done[todayKey()]??={};state.done[todayKey()][b.dataset.done]=!state.done[todayKey()][b.dataset.done];save();renderTimeline();});}
function to12(t){let[h,m]=t.split(':').map(Number);const ap=h>=12?'م':'ص';h=h%12||12;return `${h}:${String(m).padStart(2,'0')} ${ap}`}
function renderWater(){const arr=state.water[todayKey()]||Array(12).fill(false);$('#waterGrid').innerHTML=arr.map((v,i)=>`<button class="cup ${v?'done':''}" data-cup="${i}">${v?'✓':'💧'}</button>`).join('');$$('[data-cup]').forEach(b=>b.onclick=()=>{state.water[todayKey()]??=Array(12).fill(false);state.water[todayKey()][+b.dataset.cup]=!state.water[todayKey()][+b.dataset.cup];save();renderWater();});}
function renderPrograms(){const box=$('#programList');box.innerHTML=state.programs.map(p=>`<div class="program-card"><div><b>${p.name}</b><div class="task-details">${p.start||'—'} → ${p.end||'—'}</div></div><div><button class="ghost" data-active="${p.id}">${p.id===state.activeProgramId?'مفعل':'تفعيل'}</button><button class="ghost" data-edit="${p.id}">تعديل</button></div></div>`).join('');$$('[data-active]').forEach(b=>b.onclick=()=>{state.activeProgramId=b.dataset.active;save();render();});$$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));}
function openEditor(id){editingId=id;const p=id?state.programs.find(x=>x.id===id):{id:crypto.randomUUID(),name:`P${state.programs.length+1}`,start:todayKey(),end:'',instructions:'',tasks:structuredClone(defaultTasks).map(x=>({...x,id:crypto.randomUUID()}))};$('#programEditor').classList.remove('hidden');$('#editorTitle').textContent=id?'تعديل البروجرام':'إضافة بروجرام جديد';$('#programName').value=p.name;$('#programStart').value=p.start;$('#programEnd').value=p.end;$('#programInstructions').value=p.instructions;$('#taskEditor').innerHTML=p.tasks.map(taskForm).join('');$('#programEditor').dataset.temp=JSON.stringify(p);bindTaskDelete();window.scrollTo({top:$('#programEditor').offsetTop-80,behavior:'smooth'});}
function taskForm(t){return `<div class="task-edit" data-task-row="${t.id}"><input data-field="time" type="time" value="${t.time}"><input data-field="title" value="${esc(t.title)}" placeholder="عنوان المنبه"><textarea data-field="details" rows="2" placeholder="التفاصيل">${esc(t.details||'')}</textarea><select data-field="type"><option value="med" ${t.type==='med'?'selected':''}>دواء</option><option value="meal" ${t.type==='meal'?'selected':''}>أكل</option><option value="water" ${t.type==='water'?'selected':''}>مياه</option><option value="snack" ${t.type==='snack'?'selected':''}>اسناك</option><option value="walk" ${t.type==='walk'?'selected':''}>مشي</option><option value="stop" ${t.type==='stop'?'selected':''}>منع أكل</option></select><button class="danger" data-del-task="${t.id}">حذف المنبه</button></div>`}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function collectEditor(){return {id:editingId||crypto.randomUUID(),name:$('#programName').value||'Program',start:$('#programStart').value,end:$('#programEnd').value,instructions:$('#programInstructions').value,tasks:$$('[data-task-row]').map(row=>({id:row.dataset.taskRow,time:row.querySelector('[data-field=time]').value,title:row.querySelector('[data-field=title]').value,details:row.querySelector('[data-field=details]').value,type:row.querySelector('[data-field=type]').value}))}}
function bindTaskDelete(){$$('[data-del-task]').forEach(b=>b.onclick=()=>b.closest('[data-task-row]').remove());}
function renderSnacks(){if(!state.snacks.length){$('#snackGallery').innerHTML='<p class="note">لسه مفيش صور. ارفع صور الاسناكس من الزر فوق.</p>';return}$('#snackGallery').innerHTML=state.snacks.map(s=>`<div class="snack"><img src="${s.data}" alt="snack"><button data-del-snack="${s.id}">حذف</button></div>`).join('');$$('[data-del-snack]').forEach(b=>b.onclick=()=>{state.snacks=state.snacks.filter(s=>s.id!==b.dataset.delSnack);save();renderSnacks();});}
async function compressImage(file){return new Promise(res=>{const img=new Image();const r=new FileReader();r.onload=()=>{img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.76));};img.src=r.result};r.readAsDataURL(file);});}
function renderWeights(){const ul=$('#weightList');ul.innerHTML=state.weights.slice().reverse().map(w=>`<li>${w.date}: ${w.value} كجم</li>`).join('')||'<li class="note">لا يوجد تسجيل وزن بعد.</li>'}
async function askNotify(){if(!('Notification'in window)){showToast('المتصفح لا يدعم الإشعارات');return}const perm=await Notification.requestPermission();showToast(perm==='granted'?'تم تفعيل الإشعارات':'لم يتم السماح بالإشعارات');scheduleTodayAlarms();}
function scheduleTodayAlarms(){timers.forEach(clearTimeout);timers=[];const p=activeProgram();if(!('Notification'in window)||Notification.permission!=='granted')return;const now=new Date();p.tasks.forEach(t=>{const [h,m]=t.time.split(':').map(Number);const when=new Date();when.setHours(h,m,0,0);const diff=when-now;if(diff>0&&diff<86400000){timers.push(setTimeout(()=>notifyTask(t),diff));}})}
function notifyTask(t){if(state.settings.sound)$('#alarmAudio').play().catch(()=>{});if(state.settings.vibrate&&navigator.vibrate)navigator.vibrate([300,120,300]);if(navigator.serviceWorker?.controller){navigator.serviceWorker.controller.postMessage({type:'NOTIFY',title:`${icon(t.type)} ${t.title}`,body:t.details||'ميعاد المنبه',tag:t.id});}else new Notification(`${icon(t.type)} ${t.title}`,{body:t.details||'ميعاد المنبه'});}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');});
$('#notifyBtn').onclick=askNotify;$('#resetToday').onclick=()=>{delete state.done[todayKey()];delete state.water[todayKey()];save();render();};$('#saveWeight').onclick=()=>{const v=$('#weightInput').value;if(!v)return;state.weights.push({date:new Date().toLocaleString('ar-EG'),value:v});$('#weightInput').value='';save();renderWeights();};$('#addProgramBtn').onclick=()=>openEditor(null);$('#cancelProgram').onclick=()=>$('#programEditor').classList.add('hidden');$('#addTask').onclick=()=>{$('#taskEditor').insertAdjacentHTML('beforeend',taskForm({id:crypto.randomUUID(),time:'12:00',title:'منبه جديد',details:'',type:'meal'}));bindTaskDelete();};$('#saveProgram').onclick=()=>{const p=collectEditor();const i=state.programs.findIndex(x=>x.id===p.id);if(i>=0)state.programs[i]=p;else{state.programs.push(p);state.activeProgramId=p.id;}save();$('#programEditor').classList.add('hidden');render();showToast('تم حفظ البروجرام');};$('#snackUpload').onchange=async e=>{for(const f of e.target.files){const data=await compressImage(f);state.snacks.push({id:crypto.randomUUID(),name:f.name,data});}e.target.value='';save();renderSnacks();showToast('تم حفظ الصور محليًا');};$('#soundToggle').checked=state.settings.sound;$('#vibrateToggle').checked=state.settings.vibrate;$('#soundToggle').onchange=e=>{state.settings.sound=e.target.checked;save();};$('#vibrateToggle').onchange=e=>{state.settings.vibrate=e.target.checked;save();};$('#exportData').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='kerolos-diet-backup.json';a.click();};$('#importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);save();render();showToast('تم الاستيراد')};r.readAsText(f);};$('#clearAll').onclick=()=>{if(confirm('متأكد من مسح كل البيانات؟')){localStorage.removeItem(KEY);state=structuredClone(defaultState);save();render();}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden');});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
render();
